### ISSUE TITLE
请教大神，运行时抢错 node --experimental-modules src/main.mjs

### ISSUE THREAD

**Issue by hurraypub** [PatientDesperate/jyt-boot#3]
internal/modules/esm/default_resolve.js:82
  let url = moduleWrapResolve(specifier, parentURL);
            ^

Error: Cannot find module /Users/barry/Project/inbox/jyt-boot/src/utils/ajax imported from /Users/barry/Project/inbox/jyt-boot/src/main.mjs
    at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:82:13)
    at Loader.resolve (internal/modules/esm/loader.js:73:33)
    at Loader.getModuleJob (internal/modules/esm/loader.js:147:40)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:41:40)
    at link (internal/modules/esm/module_job.js:40:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

**Comment by hurraypub** [comment]
已解决

**Comment by eagermind** [comment]
请问如何解决的啊？
