### ISSUE TITLE
不能运行

### ISSUE THREAD

**Issue by felix-001** [PatientDesperate/jyt-boot#4]
(node:92121) ExperimentalWarning: The ESM module loader is experimental.
internal/modules/esm/default_resolve.js:84
  let url = moduleWrapResolve(specifier, parentURL);
            ^

Error: Cannot find module /Users/rigensen/workspace/jyt-boot/src/utils/ajax imported from /Users/rigensen/workspace/jyt-boot/src/main.mjs
    at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:84:13)
    at Loader.resolve (internal/modules/esm/loader.js:74:33)
    at Loader.getModuleJob (internal/modules/esm/loader.js:148:40)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:41:40)
    at link (internal/modules/esm/module_job.js:40:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

**Comment by yaoezi2019** [comment]
有大神指点一下么这个问题

**Comment by 33419936** [comment]
应该是依赖包的问题

**Comment by felix-001** [comment]
> 应该是依赖包的问题

咋解决呢？

**Comment by 33419936** [comment]
> > 应该是依赖包的问题
> 
> 咋解决呢？

我昨天一开始用nodejs10版本进入正常，后来使用了13的版本就出现你的错误了
更换低版本后又恢复正常
安装参考链接
https://www.linuxidc.com/Linux/2019-02/157179.htm

**Comment by felix-001** [comment]
> > > 应该是依赖包的问题
> > 
> > 
> > 咋解决呢？
> 
> 我昨天一开始用nodejs10版本进入正常，后来使用了13的版本就出现你的错误了
> 更换低版本后又恢复正常
> 安装参考链接
> https://www.linuxidc.com/Linux/2019-02/157179.htm

原来是nodejs版本不对

**Comment by 33419936** [comment]
> > > > 应该是依赖包的问题
> > > 
> > > 
> > > 咋解决呢？
> > 
> > 
> > 我昨天一开始用nodejs10版本进入正常，后来使用了13的版本就出现你的错误了
> > 更换低版本后又恢复正常
> > 安装参考链接
> > https://www.linuxidc.com/Linux/2019-02/157179.htm
> 
> 原来是nodejs版本不对

搞定了吧 不过我昨儿虽然跑起来了 但是没抢到号 还被封了

**Comment by leungyin** [comment]
> > > > > 应该是依赖包的问题
> > > > 
> > > > 
> > > > 咋解决呢？
> > > 
> > > 
> > > 我昨天一开始用nodejs10版本进入正常，后来使用了13的版本就出现你的错误了
> > > 更换低版本后又恢复正常
> > > 安装参考链接
> > > https://www.linuxidc.com/Linux/2019-02/157179.htm
> > 
> > 
> > 原来是nodejs版本不对
> 
> 搞定了吧 不过我昨儿虽然跑起来了 但是没抢到号 还被封了

是啊, 现在每抢必封....

**Comment by felix-001** [comment]
> > > > > > 应该是依赖包的问题
> > > > > 
> > > > > 
> > > > > 咋解决呢？
> > > > 
> > > > 
> > > > 我昨天一开始用nodejs10版本进入正常，后来使用了13的版本就出现你的错误了
> > > > 更换低版本后又恢复正常
> > > > 安装参考链接
> > > > https://www.linuxidc.com/Linux/2019-02/157179.htm
> > > 
> > > 
> > > 原来是nodejs版本不对
> > 
> > 
> > 搞定了吧 不过我昨儿虽然跑起来了 但是没抢到号 还被封了
> 
> 是啊, 现在每抢必封....

每次request后sleep 1-2s还会封吗

**Comment by leungyin** [comment]
> > > > > > > 应该是依赖包的问题
> > > > > > 
> > > > > > 
> > > > > > 咋解决呢？
> > > > > 
> > > > > 
> > > > > 我昨天一开始用nodejs10版本进入正常，后来使用了13的版本就出现你的错误了
> > > > > 更换低版本后又恢复正常
> > > > > 安装参考链接
> > > > > https://www.linuxidc.com/Linux/2019-02/157179.htm
> > > > 
> > > > 
> > > > 原来是nodejs版本不对
> > > 
> > > 
> > > 搞定了吧 不过我昨儿虽然跑起来了 但是没抢到号 还被封了
> > 
> > 
> > 是啊, 现在每抢必封....
> 
> 每次request后sleep 1-2s还会封吗

封, 而且还抢不到号.......

**Comment by ZSJsts** [comment]
> > > > > > > > 应该是依赖包的问题
> > > > > > > 
> > > > > > > 
> > > > > > > 咋解决呢？
> > > > > > 
> > > > > > 
> > > > > > 我昨天一开始用nodejs10版本进入正常，后来使用了13的版本就出现了你的错误了
> > > > > > 更换低版本后又恢复正常
> > > > > > 安装参考链接
> > > > > > [https://www.linuxidc.com/Linux/2019-02/157179。 htm](https://www.linuxidc.com/Linux/2019-02/157179.htm)
> > > > > 
> > > > > 
> > > > > 原来是nodejs版本不对
> > > > 
> > > > 
> > > > 搞定了吧不过我昨儿虽然跑起来了但是没抢到号还被封了
> > > 
> > > 
> > > 是啊，现在每抢必封....
> > 
> > 
> > 每次request后sleep 1-2s将封吗
> 
> 封，而且还抢不到号.......

啊？手动回车抢一次也封？那黄牛的票咋整的。按道理黄牛请求应该更频繁。
