### ISSUE TITLE
随机出现超时错误

### ISSUE THREAD

**Issue by 33419936** [PatientDesperate/jyt-boot#5]
不知道为什么，会出现超时错误，网络良好。
错误信息如下

粗错啦！ { Error: timeout of 1000ms exceeded
    at createError (/root/jyt-boot/node_modules/axios/lib/core/createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (/root/jyt-boot/node_modules/axios/lib/adapters/http.js:216:16)
    at listOnTimeout (internal/timers.js:535:17)
    at processTimers (internal/timers.js:479:7)

**Comment by ZSJsts** [comment]
> 不知道为什么，会出现超时错误，网络良好。
> 错误信息如下
> 
> 粗错啦！ { Error: timeout of 1000ms exceeded
> at createError (/root/jyt-boot/node_modules/axios/lib/core/createError.js:16:15)
> at Timeout.handleRequestTimeout [as _onTimeout] (/root/jyt-boot/node_modules/axios/lib/adapters/http.js:216:16)
> at listOnTimeout (internal/timers.js:535:17)
> at processTimers (internal/timers.js:479:7)

你们UCP是怎么抓到的，我怎么全是强制HTTPS
